import http from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),publicDir=path.join(root,'public');
const port=Number(process.env.PORT||3000),host=process.env.HOST||'127.0.0.1';
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.txt':'text/plain; charset=utf-8'};
const headers={'Content-Security-Policy':"default-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()'};
if(process.env.NODE_ENV==='production')headers['Strict-Transport-Security']='max-age=31536000; includeSubDomains';
function send(res,status,body,type='application/json; charset=utf-8'){res.writeHead(status,{...headers,'Content-Type':type,'Cache-Control':'no-store'});res.end(body)}
function json(res,status,data){send(res,status,JSON.stringify(data),mime['.json'])}
async function bodyJson(req){if(!(req.headers['content-type']||'').startsWith('application/json'))throw Object.assign(new Error('JSON required'),{status:415});let data='';for await(const c of req){data+=c;if(data.length>65536)throw Object.assign(new Error('too large'),{status:413})}return JSON.parse(data||'{}')}
function normalizeUrlPath(url){const raw=decodeURIComponent(new URL(url,'http://x').pathname);if(raw.includes('..')||raw.includes('\0'))return null;return raw}
async function staticFile(req,res){let pathname=normalizeUrlPath(req.url);if(pathname===null)return send(res,404,'Not found','text/plain; charset=utf-8');if(pathname==='/')pathname='/index.html';else if(pathname.endsWith('/'))pathname+='index.html';else if(!path.extname(pathname) && (pathname==='/404' || pathname==='/500')) pathname += '.html';let target=path.resolve(publicDir,'.'+pathname);if(!target.startsWith(publicDir+path.sep)&&target!==publicDir)return send(res,404,'Not found','text/plain; charset=utf-8');try{const s=await stat(target);if(!s.isFile())throw 0;const ext=path.extname(target);const buf=await readFile(target);res.writeHead(200,{...headers,'Content-Type':mime[ext]||'application/octet-stream','Cache-Control':ext==='.html'?'no-store':'public, max-age=3600'});res.end(buf)}catch{try{const h=await readFile(path.join(publicDir,'404.html'));res.writeHead(404,{...headers,'Content-Type':mime['.html']});res.end(h)}catch{send(res,404,'Not found','text/plain; charset=utf-8')}}}
const server=http.createServer(async(req,res)=>{try{if(req.url==='/api/health')return json(res,200,{ok:true});if(req.url==='/api/rates')return json(res,200,{as_of:new Date().toISOString(),rates:{'RUB_USDT':'0.01055','USDT_RUB':'94.10'}});if(req.url==='/api/quote'&&req.method==='POST'){const b=await bodyJson(req);const amount=BigInt(String(b.amount_minor||0));if(amount<0n)return json(res,400,{error:'invalid_amount'});return json(res,200,{amount_minor:String(amount),result_minor:String(amount*1055n/100000n),pair:b.pair||'RUB_USDT'})}if(req.url==='/api/orders'&&req.method==='POST'){const b=await bodyJson(req);if(!b.email||!b.address)return json(res,400,{error:'validation'});return json(res,201,{id:'VC-'+Date.now().toString().slice(-8),token:crypto.randomBytes(18).toString('base64url'),status:'awaiting_payment'})}return staticFile(req,res)}catch(e){return json(res,e.status||400,{error:e.message||'bad_request'})}});
if(import.meta.url===`file://${process.argv[1]}`){server.listen(port,host,()=>console.log(`Virage Change: http://${host}:${port}`))}
export {server};
